[project]
name = "uv_playground"
version = "0.1.0"
description = "uv playground"
authors = [
    {name = "SharzyL", email = "me@sharzy.in"},
]
dependencies = ["numpy>=2.2.3"]
requires-python = ">=3.12"
license = "MIT"

[project.scripts]
play = "uv_playground:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.ruff]
line-length = 120
format.quote-style = "single"
